
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-6pm-3
owner: ucsb-cs156-f23
repo_name: team02-f23-6pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjcwMzQxMDg0","is_bot":false,"login":"Garrett-Hu","name":""},"headRefName":"Garrett-Articles-DELETE","number":48,"title":"Add DELETE endpoint for a specific record in Articles table.","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-3/pull/48"},{"author":{"id":"MDQ6VXNlcjcwMzQxMDg0","is_bot":false,"login":"Garrett-Hu","name":""},"headRefName":"Garrett-Articles-PUT","number":47,"title":"Add PUT (edit) endpoint for a single record in Articles table","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-3/pull/47"},{"author":{"id":"MDQ6VXNlcjcwMzQxMDg0","is_bot":false,"login":"Garrett-Hu","name":""},"headRefName":"Garrett-Articles-GetByID","number":46,"title":"Add GET (show) endpoint for a single record in Articles table","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-3/pull/46"},{"author":{"id":"MDQ6VXNlcjcwMzQxMDg0","is_bot":false,"login":"Garrett-Hu","name":""},"headRefName":"Garrett-Articles-Controller","number":44,"title":"Create ArticlesController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-3/pull/44"},{"author":{"id":"MDQ6VXNlcjcwMzQxMDg0","is_bot":false,"login":"Garrett-Hu","name":""},"headRefName":"Garrett-Articles","number":43,"title":"Create database table for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-3/pull/43"}]
